import './components/header'
import './components/logo'
import './pages/home/components/sections/welcome'
import './pages/home/components/sections/works'
import './pages/home/components/sections/mountain'
